version: '3.7'
services:
  base-csgo:
    build:
      context: ./image/base
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: '1'
        STEAMRT_PLATFORM_VARIANT: sniper
        STEAMRT_PLATFORM_VERSION: ${CI_PR_NEW_BASE_CSGO_IMAGE_TAG}
      cache_from:
        - ghcr.io/thetredev/steamcmd:base-csgo-latest
        - thetredev-steamcmd:base-csgo
    image: thetredev-steamcmd:base-csgo
  base-legacy:
    build:
      context: ./image/base
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: '1'
        STEAMRT_PLATFORM_VARIANT: soldier
        STEAMRT_PLATFORM_VERSION: 0.20230808.56728
      cache_from:
        - ghcr.io/thetredev/steamcmd:base-legacy-latest
        - thetredev-steamcmd:base-legacy
    image: thetredev-steamcmd:base-legacy
  csgo:
    build:
      context: ./image/srcds
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: '1'
        REGISTRY_BASE_IMAGE: thetredev-steamcmd:base-csgo
        STEAMCMD_SERVER_FPSMAX: '300'
        STEAMCMD_SERVER_MAXPLAYERS: '"-maxplayers_override 32"'
        STEAMCMD_SERVER_MINRATE: '8000'
        STEAMCMD_SERVER_PORT: '27015'
        STEAMCMD_SERVER_SESSION_NAME: csgo
        STEAMCMD_SERVER_THREADS: '3'
        STEAMCMD_SERVER_TICKRATE: '128'
      cache_from:
        - ghcr.io/thetredev/steamcmd:base-csgo-latest
        - thetredev-steamcmd:srcds
    image: thetredev-steamcmd:csgo
  hlds:
    build:
      context: ./image/hlds
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: '1'
        REGISTRY_BASE_IMAGE: thetredev-steamcmd:base-legacy
        STEAMCMD_SERVER_APPID: '90'
        STEAMCMD_SERVER_MAXPLAYERS: '32'
        STEAMCMD_SERVER_PORT: '27015'
        STEAMCMD_SERVER_SESSION_NAME: hlds
      cache_from:
        - ghcr.io/thetredev/steamcmd:base-hlds-latest
        - thetredev-steamcmd:hlds
    image: thetredev-steamcmd:hlds
  srcds:
    build:
      context: ./image/srcds
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: '1'
        REGISTRY_BASE_IMAGE: thetredev-steamcmd:base-legacy
        STEAMCMD_SERVER_FPSMAX: '300'
        STEAMCMD_SERVER_MAXPLAYERS: '"+maxplayers 32"'
        STEAMCMD_SERVER_MINRATE: '8000'
        STEAMCMD_SERVER_PORT: '27015'
        STEAMCMD_SERVER_SESSION_NAME: srcds
        STEAMCMD_SERVER_THREADS: '3'
        STEAMCMD_SERVER_TICKRATE: '128'
      cache_from:
        - ghcr.io/thetredev/steamcmd:base-srcds-latest
        - thetredev-steamcmd:srcds
    image: thetredev-steamcmd:srcds
