ARG REGISTRY_BASE_IMAGE
FROM ${REGISTRY_BASE_IMAGE}

# Define a default HLDS environment for Half-Life: Opposing Force
ENV STEAMCMD_SERVER_APP_CONFIG="+app_set_config 90 mod gearbox" \
    STEAMCMD_SERVER_GAME=gearbox \
    STEAMCMD_SERVER_MAP=op4_demise \
    STEAMCMD_SERVER_SESSION_NAME=op4
