version: '3.7'

networks:
  srcds:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 0

# SRCDS image: Counter-Strike: Source
services:
  css:
    image: ghcr.io/thetredev/steamcmd:srcds-latest
    container_name: css
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      TIME_ZONE: Europe/Berlin
      STEAMCMD_UID: 1000
      STEAMCMD_GID: 1000
      STEAMCMD_SERVER_APPID: 232330
      STEAMCMD_SERVER_GAME: cstrike
      STEAMCMD_SERVER_MAP: de_dust2
      STEAMCMD_SERVER_TICKRATE: 67
      STEAMCMD_SERVER_MAXPLAYERS: 32
      STEAMCMD_SERVER_SESSION_NAME: css
    ports:
      - "27015:27015/udp"
      # enable the TCP one for RCON
      #- "27015:27015/tcp"
    volumes:
      # game server files
      - ./css:/var/lib/steamcmd/server
      # shared tmux socket directory:
      - /tmp/steamcmd:/tmp/steamcmd
    networks:
      - srcds
    security_opt:
      - no-new-privileges
    tmpfs:
      - /tmp
    ulimits:
      nofile:
        soft: 2048
        hard: 2048
