version: '3.7'

networks:
  srcds:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 0

services:
  css:
    image: ghcr.io/thetredev/steamcmd:css-latest
    container_name: css
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      TIME_ZONE: Europe/Berlin
      STEAMCMD_UID: 1000
      STEAMCMD_GID: 5000
      STEAMCMD_SERVER_APPID: 232330
      STEAMCMD_SERVER_GAME: cstrike
      STEAMCMD_SERVER_MAP: de_dust2
      STEAMCMD_SERVER_TICKRATE: 67
      STEAMCMD_SERVER_MAXPLAYERS: 32
      STEAMCMD_SERVER_SESSION_NAME: css
    ports:
      - "27015:27015/udp"
      # enable the TCP one for RCON
      #- "27015:27015/tcp"
    volumes:
      # game server files
      - ./css:/var/lib/steamcmd/server
      # shared tmux socket directory:
      #- /tmp/steamcmd:/tmp/steamcmd
    networks:
      - srcds
    security_opt:
      - no-new-privileges
    tmpfs:
      - /tmp
    ulimits:
      nofile:
        soft: 2048
        hard: 2048

  cs2:
    image: ghcr.io/thetredev/steamcmd:source2-latest
    container_name: cs2
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      TIME_ZONE: Europe/Berlin
      STEAMCMD_UID: 1000
      STEAMCMD_GID: 5000
      STEAMCMD_SERVER_APPID: 730
      STEAMCMD_SERVER_GAME: cs2
      STEAMCMD_SERVER_MAP: de_dust2
      STEAMCMD_SERVER_MAXPLAYERS: 32
      STEAMCMD_SERVER_SESSION_NAME: cs2

      # To run multiple game servers as compose services,
      # the container port must be set to the one you want exposed.
      # So, if 'css' is exposed at port 27015, then 'source2' must be exposed
      # on any other port than 27015, preferably in the 27000-27999 range.

      # We'll use 27016 for this one:
      STEAMCMD_SERVER_PORT: 27016
    ports:
      - "27016:27016/udp"
      # enable the TCP one for RCON
      #- "27016:27016/tcp"
    volumes:
      # game server files
      - ./source2:/var/lib/steamcmd/server
      # shared tmux socket directory:
      #- /tmp/steamcmd:/tmp/steamcmd
    networks:
      - srcds
    security_opt:
      - no-new-privileges
    tmpfs:
      - /tmp
    ulimits:
      nofile:
        soft: 2048
        hard: 2048
