name: Docker build and publish latest

on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  REGISTRY_IMAGE: "${{ github.repository_owner }}/${{ github.event.repository.name }}"
  GHCR_PREFIX: "ghcr.io"
  DOCKER_HUB_PREFIX: "docker.io"
  DOCKER_IMAGE_BASE_ORDER: "base srcds hlds"
  DOCKER_RETAG_SH: ".github/scripts/docker_retag.sh"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Build all images
        run: |
          for docker_base_image_type in ${DOCKER_IMAGE_BASE_ORDER}; do
            docker-compose build ${docker_base_image_type}
          done

          docker_base_images_egrep=$(echo ${DOCKER_IMAGE_BASE_ORDER} | tr " " "|")
          docker_game_images=$(docker-compose config --services | grep -Evw "(${docker_base_images_egrep})" | paste -sd " " -)

          for docker_game_image in ${docker_game_images}; do
            docker-compose build ${docker_game_image}
          done

      - name: Trivy CVE scan - base
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:base"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - base
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:base"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - hlds
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:hlds"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - hlds
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:hlds"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - srcds
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:srcds"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - srcds
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:srcds"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/hlds/hlmp
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:hlmp"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/hlds/hlmp
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:hlmp"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/hlds/cs
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:cs"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/hlds/cs
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:cs"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/hlds/czero
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:czero"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/hlds/czero
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:czero"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/hlds/dod
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:dod"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/hlds/dod
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:dod"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/hlds/dmc
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:dmc"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/hlds/dmc
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:dmc"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/hlds/op4
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:op4"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/hlds/op4
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:op4"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/hlds/tfc
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:tfc"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/hlds/tfc
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:tfc"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/srcds/bms
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:bms"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/srcds/bms
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:bms"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/srcds/css
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:css"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/srcds/css
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:css"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/srcds/csgo
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:csgo"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/srcds/csgo
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:csgo"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/srcds/dods
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:dods"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/srcds/dods
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:dods"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/srcds/gm
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:gm"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/srcds/gm
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:gm"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/srcds/hl2mp
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:hl2mp"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/srcds/hl2mp
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:hl2mp"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/srcds/l4d
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:l4d"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/srcds/l4d
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:l4d"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Trivy CVE scan - games/srcds/l4d2
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:l4d2"
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Dockle scan - games/srcds/l4d2
        uses: erzz/dockle-action@v1.3.1
        with:
          image: "${{ env.REGISTRY_IMAGE }}:l4d2"
          exit-code: '1'
          dockle-version: '0.4.5'

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS }}

      - name: Push latest images to registries
        run: |
          docker_image_types=$(docker-compose config --services | paste -sd " " -)

          for docker_image_type in ${docker_image_types}; do
            docker tag ${REGISTRY_IMAGE}:${docker_image_type} ${GHCR_PREFIX}/${REGISTRY_IMAGE}:${docker_image_type}-latest
            docker push ${GHCR_PREFIX}/${REGISTRY_IMAGE}:${docker_image_type}-latest

            docker tag ${REGISTRY_IMAGE}:${docker_image_type} ${DOCKER_HUB_PREFIX}/${REGISTRY_IMAGE}:${docker_image_type}-latest
            docker push ${DOCKER_HUB_PREFIX}/${REGISTRY_IMAGE}:${docker_image_type}-latest
          done
